Logfile created with verbose level LOG_ONLY on 30/12/2024 at 22:22:15. Have fun <3

[22:22:15] INFO    : MessageLogger verbose type updating from LOG_ONLY to INFO
[22:22:15] INFO    : MessageLogger verbose type updated from LOG_ONLY to INFO
[22:22:15] INFO    : Imported settings: {'_comment0': 'Supported levels: [NONE, LOG_ONLY, ERROR, WARNING, CRUCIAL, INFO]', 'verbose_type': 'INFO', '_comment1': 'window_resolution irrelevant unless fullscreen is true; fullscreen overwride window_resolution to monitor resolution', 'window_resolution': [0, 0], 'fullscreen': True, '_comment2': 'setting max_fps to 0 disables the fps cap; vsync will overwride max_fps to match window fps to monitor fps', 'max_fps': 0, 'vsync': True, '_comment3': 'raw_mouse_input will enable raw mouse movement (bypass windows mouse acceleration)', 'raw_mouse_input': True, 'mouse_sensitivity': 1, '_comment4': "Avalable keys: https://www.glfw.org/docs/3.3/group__keys.html (Remove the 'GLFW_KEY_' prefix)", 'key_binds': {'jump': 'SPACE', 'forward': 'W', 'back': 'S', 'left': 'A', 'right': 'D'}}
[22:22:15] INFO    : Window variable validation passed. Variables: {}
[22:22:15] INFO    : Window creation passed. Variables: {'size': Size(width=1920, height=1080), 'caption': 'Into Havoc', 'fullscreen': True, 'vsync': True, 'max_fps': 0, 'raw_mouse_input': True, 'center_cursor': True, 'hide_cursor': True, 'monitor': <glfw.LP__GLFWmonitor object at 0x0000025F6E785DD0>, 'video_mode': GLFWvidmode(size=Size(width=1920, height=1080), bits=Bits(red=8, green=8, blue=8), refresh_rate=60), 'display_size': Size(width=1920, height=1080), 'aspect_ratio': 1.7777777777777777, 'window': <glfw.LP__GLFWwindow object at 0x0000025F6E785E50>}
[22:22:15] INFO    : Setting up Graphics Engine
[22:22:15] INFO    : Creating shader default
[22:22:15] INFO    : No texture in this shader.
[22:22:15] ERROR   : Fatal termination error:

Traceback (most recent call last):
  File "C:\Users\laket\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\laket\OneDrive\Documents\Code\GitHub\PyCode\LakeGraphicsFramework\example.py", line 30, in catch_main
    main()
  File "c:\Users\laket\OneDrive\Documents\Code\GitHub\PyCode\LakeGraphicsFramework\example.py", line 42, in main
    window = lgf.Window(settings["window_resolution"], CAPTION, settings["fullscreen"], settings["vsync"], settings["max_fps"], settings["raw_mouse_input"], True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\laket\OneDrive\Documents\Code\GitHub\PyCode\LakeGraphicsFramework\LakeGraphicsFramework.py", line 122, in __init__
    self.graphics_engine = GraphicsEngine(fovy, self.aspect_ratio, near, far, skybox_color)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\laket\OneDrive\Documents\Code\GitHub\PyCode\LakeGraphicsFramework\LakeGraphicsFramework.py", line 312, in __init__
    self.shaders["default"] = Shader("default", SHADERS_PATH + DEFAULT_VERT_SHADER, SHADERS_PATH + DEFAULT_FRAG_SHADER, fovy, aspect, near, far)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\laket\OneDrive\Documents\Code\GitHub\PyCode\LakeGraphicsFramework\LakeGraphicsFramework.py", line 231, in __init__
    self._init_perspective_projection(self.uniform_handles["projection"], fovy, aspect, near, far)
  File "c:\Users\laket\OneDrive\Documents\Code\GitHub\PyCode\LakeGraphicsFramework\LakeGraphicsFramework.py", line 288, in _init_perspective_projection
    gl.glUniformMatrix4fv(projection_handle, 1, gl.GL_FALSE, projection_transform)
  File "C:\Users\laket\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laket\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\wrapper.py", line 700, in wrapperCall
    raise err
  File "C:\Users\laket\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\wrapper.py", line 693, in wrapperCall
    result = wrappedOperation( *cArguments )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laket\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laket\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glUniformMatrix4fv,
	pyArgs = (
		2,
		1,
		GL_FALSE,
		array([[ 0.47199354,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.83909965,  0.        ,  0.      ...,
	),
	cArgs = (
		2,
		1,
		GL_FALSE,
		array([[ 0.47199354,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.83909965,  0.        ,  0.      ...,
	),
	cArguments = (
		2,
		1,
		GL_FALSE,
		array([[ 0.47199354,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.83909965,  0.        ,  0.      ...,
	)
)

[22:22:15] INFO    : Program terminating
